### ISSUE TITLE
error starting 

### ISSUE THREAD

**Issue by dfcarpenter** [kittoframework/demo#1] opened 2016-10-29 03:34 UTC
Having issues running the local dev server. Followed directions for install and running.

Elixir 1.3.3 

```
mix kitto.server

18:13:37.235 [info]  Starting Kitto server on port 4000
 51% 154/225 build modules
=INFO REPORT==== 28-Oct-2016::18:13:42 ===
    application: logger
    exited: stopped
    type: temporary

=INFO REPORT==== 28-Oct-2016::18:13:42 ===
    application: ranch
    exited: shutdown
    type: temporary
** (Mix) Could not start application kitto: Kitto.start(:normal, []) returned an error: shutdown: failed to start child: Kitto.Runner
    ** (EXIT) an exception was raised:
        ** (CompileError) jobs/buzzwords.ex:1: module Kitto.Job.DSL is not loaded and could not be found
            (elixir) expanding macro: Kernel.use/1
            jobs/buzzwords.ex:1: (file)


```

**Comment by zorbash** [comment] 2016-10-29 08:31
A quick workaround is to specify a package version like `{:kitto, "0.1.1"}` in `mix.exs`.

Care to specify the output of `mix hex.info`?

Also after running `mix deps.clean kitto && mix deps.get` i'd like you to 

``` bash
cd deps/kitto
```

and

Paste the output of:

``` bash
git ls-files | grep job/
```

And of:

```
git log -1 --format="%h"
```

**Comment by dfcarpenter** [comment] 2016-10-29 16:53
Seeing your latest push I ended up recloning and getting the latest version and after adding adding some keys and secrets for Twitter everything is working just fine

**Comment by zorbash** [comment] 2016-10-29 17:48
Great! I'm closing this, since you got it working and there are no steps to reproduce the issue. 

I tried with various versions of hex:
- v0.14.0
- v0.13.2
- v0.12.1
- v0.11.1
- v0.11.2

but couldn't get it to emit the reported error.

**Closed as completed by zorbash** 2016-10-29 17:48 UTC
Labels: bug
